version: "3.5"

services:
  react:
    build: frontend/.
    container_name: react
    depends_on:
      - postgresql
    ports:
      - "3000:3000"
    networks:
      transcendence:
        ipv4_address: 152.10.2.1
  django:
    build: backend/.
    container_name: django
    ports:
      - "8000:8000"
    networks:
      transcendence:
        ipv4_address: 152.10.2.2
    depends_on:
      - postgresql
      - react
    environment:
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
  postgresql:
    build: db/.
    container_name: postgresql
    networks:
      transcendence:
        ipv4_address: 152.10.2.3
    environment:
      - PGDATA=${PGDATA}
      - LD_LIBRARY_PATH=${LD_LIBRARY_PATH}
      - PATH=${PATH}
      - MANPATH=${MANPATH}

networks:
  transcendence:
    driver: bridge
    ipam:
      config:
        - subnet: 152.10.0.0/16
