# Generated by Django 5.0.3 on 2024-03-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=64)),
                ('token_type', models.CharField(max_length=6)),
                ('expires_in', models.IntegerField()),
                ('refresh_token', models.CharField(max_length=64)),
                ('scope', models.CharField(max_length=6)),
                ('created_at', models.DateField()),
                ('secret_valid_until', models.DateField()),
            ],
        ),
    ]
