# Generated by Django 5.0.3 on 2024-03-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='expires_in',
        ),
    ]
