# Generated by Django 5.0.3 on 2024-03-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_remove_token_expires_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='token',
            name='secret_valid_until',
        ),
    ]
