# Generated by Django 5.0.3 on 2024-03-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_remove_token_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='created_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='expires_in',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='secret_valid_until',
            field=models.IntegerField(null=True),
        ),
    ]
