# Generated by Django 5.0.3 on 2024-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_tokendata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendata',
            name='access_token',
            field=models.JSONField(default='{}', verbose_name='TokenDetails'),
        ),
    ]
